platform :ios, '9.0'

target 'ImaginaryDemo' do
  use_frameworks!

  pod 'Imaginary', path: '../../'
  pod 'SwiftHash', git: 'https://github.com/onmyway133/SwiftHash', tag: '2.0.0'
  pod 'Cache', git: 'https://github.com/hyperoslo/Cache', branch: 'master'

end
